name: bargainz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  camera: ^0.11.0+1
  cloud_firestore: ^5.0.1
  data_table_2: ^2.5.15
  firebase_core: ^3.1.0
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_slidable: ^3.1.0
  form_builder_validators: ^10.0.1
  google_mlkit_barcode_scanning: ^0.12.0
  path: ^1.9.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#297373"
  image: assets/images/logo.png
  android_12:
    color: "#297373"
    image: assets/images/logo.png
  android: true
